<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>b</string>
	</array>
	<key>name</key>
	<string>Brotorift</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.node.brotorift</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant.language.brotorift</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.node.brotorift</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>node</string>
			<key>match</key>
			<string>\b(node)\s+(unity|scala)\s+([A-Za-z_][A-Za-z0-9_]*)</string>
			<key>name</key>
			<string>meta.node.brotorift</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.as.brotorift</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.as.brotorift</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>as</string>
			<key>match</key>
			<string>\b(as)\s+([A-Z][A-Za-z0-9_]*)</string>
			<key>name</key>
			<string>meta.as.brotorift</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.namespace.brotorift</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.namespace.head.brotorift</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.namespace.tail.brotorift</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>namespace</string>
			<key>match</key>
			<string>\b(namespace)\s+([A-Za-z_][A-Za-z0-9_]*)(.[A-Za-z_][A-Za-z0-9_]*)*</string>
			<key>name</key>
			<string>meta.namespace.brotorift</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>document</string>
			<key>match</key>
			<string>\#.*</string>
			<key>name</key>
			<string>comment.line.number-sign.node.brotorift</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(enum)\s+([A-Z_][A-Za-z0-9_]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.enum.brotorift</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.enum.brotorift</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>enum</string>
			<key>end</key>
			<string>\b(end)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.end.brotorift</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.enum.brotorift</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.element.brotorift</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>enum element</string>
					<key>match</key>
					<string>\b([A-Z_][A-Za-z0-9_]*)</string>
					<key>name</key>
					<string>meta.element.brotorift</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.hexadecimal.brotorift</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>enum value (hexadecimal)</string>
					<key>match</key>
					<string>=\s*(0[xX][0-9a-fA-F]+)</string>
					<key>name</key>
					<string>meta.element.value.brotorift</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.decimal.brotorift</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>enum value (decimal)</string>
					<key>match</key>
					<string>=\s*((\+|-)?\d+)</string>
					<key>name</key>
					<string>meta.element.value.brotorift</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>document</string>
					<key>match</key>
					<string>\#.*</string>
					<key>name</key>
					<string>comment.line.number-sign.enum.brotorift</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(struct)\s+([A-Za-z_][A-Za-z0-9_]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.struct.brotorift</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.struct.brotorift</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>struct</string>
			<key>end</key>
			<string>\b(end)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.end.brotorift</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.struct.brotorift</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.member.type.brotorift</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>struct member type</string>
					<key>match</key>
					<string>\b([A-Z][A-Za-z0-9_]*)</string>
					<key>name</key>
					<string>meta.member.brotorift</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.member.brotorift</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>struct member name</string>
					<key>match</key>
					<string>\b([a-z_][A-Za-z0-9_]*)</string>
					<key>name</key>
					<string>meta.member.brotorift</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>document</string>
					<key>match</key>
					<string>\#.*</string>
					<key>name</key>
					<string>comment.line.number-sign.struct.brotorift</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(direction)\s+([A-Z][A-Za-z0-9_]*)\s*(-&gt;|&lt;-)\s*([A-Z][A-Za-z0-9_]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.direction.brotorift</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.node.brotorift</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.brotorift</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.node.brotorift</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>direction</string>
			<key>end</key>
			<string>\b(end)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.end.brotorift</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.direction.brotorift</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(message)\s+([A-Z][A-Za-z0-9_]*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.message.brotorift</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.message.brotorift</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>message</string>
					<key>end</key>
					<string>\b(end)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.end.brotorift</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.message.brotorift</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.constant.member.type.brotorift</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>message member type</string>
							<key>match</key>
							<string>\b([A-Z][A-Za-z0-9_]*)</string>
							<key>name</key>
							<string>meta.member.brotorift</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.member.brotorift</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>message member name</string>
							<key>match</key>
							<string>\b([a-z_][A-Za-z0-9_]*)</string>
							<key>name</key>
							<string>meta.member.brotorift</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>document</string>
							<key>match</key>
							<string>\#.*</string>
							<key>name</key>
							<string>comment.line.number-sign.message.brotorift</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(sequence)\s+([A-Z][A-Za-z0-9_]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.sequence.brotorift</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.brotorift</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>sequence</string>
			<key>end</key>
			<string>\b(end)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.end.brotorift</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.sequence.brotorift</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.node.brotorift</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.brotorift</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.node.brotorift</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.message.brotorift</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>step</string>
					<key>match</key>
					<string>([A-Z][A-Za-z0-9_]*)\s*(-&gt;|&lt;-)\s*([A-Z][A-Za-z0-9_]*)\s*:\s*([A-Z][A-Za-z0-9_]*)</string>
					<key>name</key>
					<string>meta.step.brotorift</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>document</string>
					<key>match</key>
					<string>\#.*</string>
					<key>name</key>
					<string>comment.line.number-sign.message.brotorift</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.b</string>
	<key>uuid</key>
	<string>539d865e-661d-4270-a3fc-84fee84d2518</string>
</dict>
</plist>
